
export const ON_AUTH_STATE_CHANGED = 'ON_AUTH_STATE_CHANGED';
export const LOGOUT = 'LOGOUT';
export const SET_USER_PROFILE = 'SET_USER_PROFILE';
export const SET_DOG_PROFILE = 'SET_DOG_PROFILE';
export const SET_DOG_PROFILES = 'SET_DOG_PROFILES';
export const ADD_DOG_PROFILE = 'ADD_DOG_PROFILE';
export const EDIT_DOG_PROFILE = 'EDIT_DOG_PROFILE';
export const REMOVE_DOG_PROFILE = 'REMOVE_DOG_PROFILE';
export const CLEAR_PROFILES = 'CLEAR_PROFILES';
export const SET_GOOGLE_MAPS_API_KEY = 'SET_GOOGLE_MAPS_API_KEY';