import defaultButton from './Button';
import defaultContainer from './Container';
import defaultHeader from './Header';
import defaultScreenContainer from './ScreenContainer';
import defaultText from './Text';
import defaultCarousel from './Carousel';
import defaultImage from './Image';
import defaultValidatedTextInput from './ValidatedTextInput';
import defaultTextLink from './TextLink';
import defaultAvatar from './Avatar';
import defaultImageSelector from './ImageSelector';
import defaultHeaderButton from './HeaderButton';
import defaultSearchPickerSingle from './SearchPickerSingle';
import defaultSearchPickerMulti from './SearchPickerMulti';
import defaultSwitchSelector from './SwitchSelector';
import defaultDateTimePicker from './DatePicker';
import defaultScrollView from './ScrollView';
import defaultKeyboardAvoidingView from './KeyboardAvoidingView';
import defaultPasswordTextInput from './PasswordTextInput';
import defaultTextInput from './TextInput';
import defaultPickerSelect from './PickerSelect';
import defaultGpsButton from './GpsButton';
import defaultModal from './Modal';
import defaultDivider from './Divider';

export const Button = defaultButton;
export const Container = defaultContainer;
export const Header = defaultHeader;
export const ScreenContainer = defaultScreenContainer;
export const Text = defaultText;
export const Carousel = defaultCarousel;
export const Image = defaultImage;
export const ValidatedTextInput = defaultValidatedTextInput;
export const TextLink = defaultTextLink;
export const Avatar = defaultAvatar;
export const ImageSelector = defaultImageSelector;
export const HeaderButton = defaultHeaderButton;
export const SearchPickerSingle = defaultSearchPickerSingle;
export const SearchPickerMulti = defaultSearchPickerMulti;
export const SwitchSelector = defaultSwitchSelector;
export const DateTimePicker = defaultDateTimePicker;
export const ScrollView = defaultScrollView;
export const KeyboardAvoidingView = defaultKeyboardAvoidingView;
export const PasswordTextInput = defaultPasswordTextInput;
export const TextInput = defaultTextInput;
export const PickerSelect = defaultPickerSelect;
export const GpsButton = defaultGpsButton;
export const Modal = defaultModal;
export const Divider = defaultDivider;